### PR TITLE
updating the readme

### PR DESCRIPTION
**Pull request by pranshurastogi29**
this will provide link on kaggle auth and public implementation of project

### CODE REVIEW

**Comment by ucalyptus** [comment]
@pranshurastogi29 any hosted link for me to review ur nb?

**Comment by ucalyptus** [comment]
nevermind , I got this https://app.reviewnb.com/ucalyptus/Pneumothorax-Segmentation-using-Hypercolumns/pull/36/files/

**Comment by ucalyptus** [comment]
LGTM

**Comment by pranshurastogi29** [comment]
yes you can see the notebook on colab by going through the link

**Pull request merged**
