### PR TITLE
Updated_README.md

### PR DESCRIPTION
**Pull request by pranshurastogi29**

### CODE REVIEW

**Comment by pranshurastogi29** [comment]
siimacr-pneumothorax-segmentation.ipynb file is public implementation of the note book with kaggle authorization this note book is implemented in colab if some one wants to try then i will put the link in the readme

**Comment by pranshurastogi29** [comment]
lastly i have added radam  in the same colab notebook and it runs fine

**Comment by ucalyptus** [comment]
@pranshurastogi29 can you send me a public nbviewer hosted link to the notebook you committed?

**Comment by pranshurastogi29** [comment]
Ok i will give the link

**Comment by ucalyptus** [comment]
Also please make different PR for each tasks.As a maintainer it's not possible to track every little change if all commits are made into one PR. I mentioned Issues for a reason.

**Pull request closed without merging**
