### PR TITLE
Having some trouble. Please help

### LINKED ISSUE #2: Refactoring ipynb
Find the different parts of the code from the notebook and put them under different modules.

### PR DESCRIPTION
**Pull request by lkdmttg7**
Partially fixes #2

### CODE REVIEW

**Comment by ucalyptus** [comment]
What happened?

**Comment by lkdmttg7** [comment]
The code is kind of complicated. Need some guidance.

**Comment by ucalyptus** [comment]
Put each function in a separate module. Link them like you use in Python.
Let me know if anything else.
Also, you can see how it is to be done from ucalyptus/Detecting-Ships

**Comment by lkdmttg7** [comment]
Actually I am getting confused in what to put in preparing and so  on. Is the input file correct?

**Pull request closed without merging**
